# Generated by Django 4.2.7 on 2024-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
