# Generated by Django 4.2.7 on 2024-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_books_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price_after_discount',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
